---
Transform: AWS::SecretsManager-2020-07-23
Description: This is an example template to demonstrate CloudFormation resources for
  Secrets Manager
Parameters:
  TestVPC:
    Type: String
    Description: VPC ID for deploying the RDS instance
  TestPublicSubnet1:
    Type: String
    Description: Public Subnet ID for deploying the RDS instance
  TestPublicSubnet2:
    Type: String
    Description: Public Subnet ID for deploying the RDS instance
  TestPublicAccessSg:
    Type: String
    Description: Public access Security Group for accessing from your local. Only do this for testing
Resources:
  #This is a Secret resource with a randomly generated password in its SecretString JSON.
  MyRDSInstanceSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: This is my rds instance secret
      Name: RDSSecretsDemo
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"
      Tags:
        - Key: AppName
          Value: MyApp

  #This is an RDS instance resource. Its master username and password use dynamic references to resolve values from
  #SecretsManager. The dynamic reference guarantees that CloudFormation will not log or persist the resolved value
  #We sub the Secret resource's logical id in order to construct the dynamic reference, since the Secret's name is being #generated by CloudFormation
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      PubliclyAccessible: true # Don't do this in production
      DBSubnetGroupName:
        Ref: MyDBSubnetGroup
      MasterUsername:
        Fn::Sub: "{{resolve:secretsmanager:${MyRDSInstanceSecret}::username}}"
      MasterUserPassword:
        Fn::Sub: "{{resolve:secretsmanager:${MyRDSInstanceSecret}::password}}"
      BackupRetentionPeriod: 0
      VPCSecurityGroups:
        - Ref: TestPublicAccessSg
  #Database subnet group for the RDS instance
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Test Group
      SubnetIds:
        - Ref: TestPublicSubnet1
        - Ref: TestPublicSubnet2
  #This is a SecretTargetAttachment resource which updates the referenced Secret resource with properties about
  #the referenced RDS instance
  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId:
        Ref: MyRDSInstanceSecret
      TargetId:
        Ref: MyDBInstance
      TargetType: AWS::RDS::DBInstance